# yml version
version: '3'

services:

  backend:
    build:
      context: ./backend
      args:
        DJANGO_ALLOWED_HOSTS: *
        DJANGO_SECRET_KEY: *
        DJANGO_CORS_ORIGIN_WHITELIST: *
    command: gunicorn dodge_angle.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - database

  frontend:
    build:
      context: ./blog_frontend
      args:
        API_URL: *
    volumes:
      - build_folder:/frontend/build

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend

  database:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: dodge_angle
      MYSQL_USER: normalfriends
      MYSQL_PASSWORD: *
      MYSQL_ROOT_PASSWORD: *
      MYSQL_ROOT_HOST: '%'
    volumes:
      - persistent_data:/var/lib/mysql

volumes:
  build_folder:
  persistent_data: